sonar.projectKey=devsetgo_ai-pr-assistant
sonar.organization=devsetgo

sonar.sources=pr_description,autofill_description.py
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=ai-pr-assistant
sonar.projectVersion=26.09.19-002

sonar.language=python
sonar.python.version=3.14

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8